services:
  tenant-service:
    build:
      context: ..
      dockerfile: ./tenant-service/Dockerfile.dev
    container_name: tenant-service
    ports:
      - "9001:8080"
      - "9051:9090"
      - "5001:5005" # Expose debug port
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://tenant-db:5432/tenant-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: tenant-redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      SPRING_KAFKA_CONSUMER_GROUP_ID: tenant-consumer-group
      OTEL_SERVICE_NAME: tenant-service
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_TRACES_EXPORTER: otlp
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment=dev
    depends_on:
      - tenant-db
      - tenant-redis
    develop:
      watch:
        - action: sync+restart
          path: ../tenant-service/src
          target: /app/tenant-service/src
          ignore:
            - node_modules
            - target
        - action: rebuild
          path: ../tenant-service/pom.xml
    networks:
      - notification-net
    volumes:
      - ~/.m2:/root/.m2
      - ../tenant-service/src:/app/tenant-service/src
      - ../tenant-service/pom.xml:/app/tenant-service/pom.xml
      - ../agents/opentelemetry-javaagent.jar:/otel-agent.jar:ro

  tenant-db:
    image: postgres:16
    container_name: tenant-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tenant-db
    ports:
      - "5501:5432"
    volumes:
      - tenant_pgdata:/var/lib/postgresql/data
    networks:
      - notification-net

  tenant-redis:
    image: redis:7
    container_name: tenant-redis
    restart: always
    ports:
      - "6001:6379"
    networks:
      - notification-net

networks:
  notification-net:
    external: true

volumes:
  tenant_pgdata:
