services:
  notification-service:
    build:
      context: ..
      dockerfile: ./notification-service/Dockerfile.dev
    container_name: notification-service
    ports:
      - "9002:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://notification-db:5432/notification_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: notification-redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_KAFKA_CONSUMER_GROUP_ID: notification-consumer-group
      GRPC_CLIENT_TENANT_SERVICE_ADDRESS: static://tenant-service:9090
    depends_on:
      - notification-db
      - notification-redis

    # ===== WATCH MODE CONFIGURATION =====
    develop:
      watch:
        - action: sync+restart
          path: ../notification-service/src
          target: /app/notification-service/src
          ignore:
            - node_modules
            - target
        - action: rebuild
          path: ../notification-service/pom.xml

    # ===== VOLUME MOUNTS =====
    volumes:
      - ~/.m2:/root/.m2
      - ../notification-service/src:/app/notification-service/src
      - ../notification-service/pom.xml:/app/notification-service/pom.xml

    networks:
      - notification-net

  notification-db:
    image: postgres:16
    container_name: notification-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notification_db
    ports:
      - "5502:5432"
    volumes:
      - notification_pgdata:/var/lib/postgresql/data
    networks:
      - notification-net

  notification-redis:
    image: redis:7
    container_name: notification-redis
    restart: always
    ports:
      - "6002:6379"
    networks:
      - notification-net

networks:
  notification-net:
    external: true

volumes:
  notification_pgdata: